### ISSUE TITLE
VAPID Public/Private key

### ISSUE THREAD

**Issue by fenix-hub** [st-user/zerodep-web-push-java#13]
Could you please give an example of Public/Private keys?
I tried to generate VAPID keys both from any node.js service and openssl and I can't get this library work with any of those.

**Comment by st-user** [comment]
As these examples show, a VAPID key pair for this library can be generated like the following:

``` bash
openssl ecparam -genkey -name prime256v1 -noout -out my-private.pem
openssl pkcs8 -in my-private.pem -topk8 -nocrypt -out my-private_pkcs8.pem
openssl ec -in my-private.pem -pubout -conv_form uncompressed -out my-pub.pem

# 'my-private_pkcs8.pem' and 'my-pub.pem' are used in these examples.
```

Also, you can generate a key pair in DER format.

``` bash
openssl ecparam -genkey -name prime256v1 -noout -out my-private.pem
openssl pkcs8 -in my-private.pem -topk8 -nocrypt -outform der -out my-private_pkcs8.der
openssl ec -in my-private.pem -pubout -conv_form uncompressed -outform der -out my-pub.der
```
``` java

Path derPath = new File("my-private_pkcs8.der").toPath();
PrivateKeySource derSource = PrivateKeySources.ofDERFile(derPath);
.... 

Path derPath = new File("my-pub.der").toPath();
PublicKeySource derSource = PublicKeySources.ofDERFile(derPath);

```
The examples above (and other examples) are described in the java docs of [PrivateKeySources](https://github.com/st-user/zerodep-web-push-java/blob/main/src/main/java/com/zerodeplibs/webpush/key/PrivateKeySources.java) and [PublicKeySources](https://github.com/st-user/zerodep-web-push-java/blob/main/src/main/java/com/zerodeplibs/webpush/key/PublicKeySources.java)

**Comment by fenix-hub** [comment]
Thank you very much!
I generated the keys with your snippets and now I'm able to correctly load the files.
Should the public key's content be the one to directly share with the client?
When I try to push a message, I receive this error
```
{"code": 401, "errno": 109, "error": "Unauthorized", "more_info": "http://autopush.readthedocs.io/en/latest/http.html#error-codes", "message": "Request did not validate missing authorization header: Key mismatch"}
```

**Comment by st-user** [comment]
> Should the public key content be the one to directly share with the client?

Yes, a public key for VAPID should be sent to browsers and browsers should subscribe push notifications with the public key (like the example below).

``` javascript

    const serverPublicKey = await fetch('/getPublicKey')
                                    .then(response => response.arrayBuffer());

    await navigator.serviceWorker.register('/app-service-worker.js');

    const registration = await navigator.serviceWorker.ready;
    const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: serverPublicKey
    });

```
(https://github.com/st-user/zerodep-web-push-java-example/blob/main/src/main/resources/static/main.js)

 > When I try to push a message, I receive this error

 - What browser(Safari or Google Chrome? Or the others?) do you use?  Some browsers may not support push notification.
 - Does your browser successfully subscribe the push notification?  
 - Is the error response received on your java application? 

This library provides the functionality for 'Application Server' (detail: please see [the blog post](https://golb.hplar.ch/2019/08/webpush-java.html#architecture)). So it may not be available in other use cases.

**Comment by st-user** [comment]
I couldn't reproduce the error exactly but the following code doesn't work for me too.

``` bash
openssl ec -in my-private.pem -pubout -conv_form uncompressed -out my-pub.pem
>>>
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE4T6d5v+sdabOKpidLyXZBISnNY1L
qt+XWvpgLiPERnWDE3Xrlqe4wFo039Zkb6AtMaM3L9Ab0Ke4OnViKuAvIw==
-----END PUBLIC KEY-----
```
``` javascript
const strPublicKey = `MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE4T6d5v+sdabOKpidLyXZBISnNY1Lqt+XWvpgLiPERnWDE3Xrlqe4wFo039Zkb6AtMaM3L9Ab0Ke4OnViKuAvIw==`;

const subscription = await registration.pushManager.subscribe({
    userVisibleOnly: true,
    applicationServerKey: strPublicKey
});
```

Because:

 - [Push API](https://www.w3.org/TR/push-api/#pushsubscriptionoptions-interface) requires that `applicationServerKey` is encoded in the uncompressed form described in [ANSI-X9-62] Annex A (that is, 65 octets, starting with an 0x04 octet).
 - Also Push API requires that `applicationServerKey` is encoded using base64url(without padding) when it is provided as a DOMString.
 - On the other hand, the public key generated with openssl like above is encoded according to the X.509 standard and encoded using base64(with padding).


### possible work around

The following code works.

```
openssl ec -in my-private.pem -pubout -conv_form uncompressed -out my-pub.pem
``` 
``` java
PublicKeySource publicKeySource = PublicKeySources.ofPEMFile(new File("my-pub.pem").toPath());
byte[] pkBytes = publicKeySource.extractBytesInUncompressedForm();
System.out.println(Base64.getUrlEncoder().withoutPadding().encodeToString(pkBytes));

(output>>>)

BOE-neb_rHWmziqYnS8l2QSEpzWNS6rfl1r6YC4jxEZ1gxN165anuMBaNN_WZG-gLTGjNy_QG9CnuDp1YirgLyM
```

``` javascript

const strPublicKey = `BOE-neb_rHWmziqYnS8l2QSEpzWNS6rfl1r6YC4jxEZ1gxN165anuMBaNN_WZG-gLTGjNy_QG9CnuDp1YirgLyM`

const subscription = await registration.pushManager.subscribe({
    userVisibleOnly: true,
    applicationServerKey: strPublicKey
});
```

**Comment by fenix-hub** [comment]
Thank you very much, it works like a charm now!
I came from another Java web-push library, and it didn't require creating these certificates and encoding/decoding them in code manually. But I prefer this library instead since it's more compatible and elastic.
Anyway with all your explanation everything works. I think that this kind of flow could be documented for newbies that come from "more standardized" libreries.
Here's a snippet of my flow

1. Create keys
```
openssl ecparam -genkey -name prime256v1 -noout -out soruceKey.pem
openssl pkcs8 -in soruceKey.pem -topk8 -nocrypt -out vapidPrivateKey.pem
openssl ec -in sourceKey.pem -pubout -conv_form uncompressed -out vapidPublicKey.pem
```

2. Create a CDI for VapidKeyPair injection
<details>
<summary>Code</summary>

```java
public class VAPIDKeyPairService {
    
    private VAPIDKeyPair vapidKeyPair;

    VAPIDKeyPairService(
        @ConfigProperty(name = "push.vapid.publicKey.location", defaultValue = "")
        String vapidPublicKey,
        @ConfigProperty(name = "push.vapid.privateKey.location", defaultValue = "")
        String vapidPrivateKey
    ) throws IOException {
        this.vapidKeyPair = VAPIDKeyPairs.of(
            PrivateKeySources.ofPEMFile(new File(getClass().getResource("/"+vapidPrivateKey).getPath()).toPath()), 
            PublicKeySources.ofPEMFile(new File(getClass().getResource("/"+vapidPublicKey).getPath()).toPath())
        );
    }

    public VAPIDKeyPair getVapidKeyPair() {
        return this.vapidKeyPair;
    }


    public String getVAPIDPublicKey() {
        return Base64.getUrlEncoder().withoutPadding().encodeToString(this.vapidKeyPair.extractPublicKeyInUncompressedForm());
    }

}
```
</details>

4. Send a push using `VAPIDKeyPairService.getVapidKeyPair()` in the `StandardHttpClientRequestPreparer` builder
5. Expose an endpoint such as `GET /publicKey` executing the `getVAPIDPublicKey()` to expose the public key on the frontend

**Comment by st-user** [comment]
I'm glad to help you and thank you for useful suggestions!

 > I think that this kind of flow could be documented for newbies that come from "more standardized" libreries.

I think so too. It is slightly difficult for newbies to use this library. I'm going to document such a flow in the project README.

 > Expose an endpoint such as GET /publicKey executing the getVAPIDPublicKey() to expose the public key on the frontend

I think the base64url version of VAPID public key is useful in some use cases. 
So I'm going to add a method used to get a base64url public key to `VAPIDKeyPair.java` and `PublicKeySource.java` (such as `extractBase64PublicKeyInUncompressedForm`) .

For your information, a public key don't have to be converted to base64url string. it can also be sent as `byte[]` for example:

``` java
    @Autowired
    private VAPIDKeyPair vapidKeyPair;

    @GetMapping("/getPublicKey")
    public byte[] getPublicKey() {
        return vapidKeyPair.extractPublicKeyInUncompressedForm();
    }

```
``` javascript
    const serverPublicKey = await fetch('/getPublicKey')
                                    .then(response => response.arrayBuffer());

    const subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: serverPublicKey
    });
```
([The example projects](https://github.com/st-user/zerodep-web-push-java-example) uses this way.)

**Comment by fenix-hub** [comment]
Hi, I didn't want to spam your issues just for this little question, since it is related, but would it be possible to generate the same keys, just as doing it from openssl, but directly from java throuh your library?
Or it would require a custom implementation?

**Comment by st-user** [comment]
Currently this library doesn't provide a feature for generating VAPID key pairs.
But you can easily instantiate `VAPIDKeyPair` by generating the key pair programmatically like:

``` java

        KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance("EC");
        keyPairGenerator.initialize(new ECGenParameterSpec("secp256r1"));

        KeyPair keyPair = keyPairGenerator.genKeyPair();
        ECPrivateKey privateKey = (ECPrivateKey) keyPair.getPrivate();
        ECPublicKey publicKey = (ECPublicKey) keyPair.getPublic();

        // You may have to save the key pair somewhere.
       //  savePrivateKey(privateKey.getEncoded());
       //  savePublicKey(publicKey.getEncoded());


        return VAPIDKeyPairs.of(
            PrivateKeySources.ofECPrivateKey(privateKey),
            PublicKeySources.ofECPublicKey(publicKey)
        );

```

If you do that, I assume that you have to save the key pair somewhere(e.g. RDB, NoSQL database etc) .
If you don't save the key pair, you loose the key pair if you reboot your java application.

**Comment by fenix-hub** [comment]
Is it correct that `ECPublicKey`
`Base64.getUrlEncoder().withoutPadding().encodeToString(vapidKeyPair.extractPublicKeyInUncompressedForm());`
and
`Base64.getUrlEncoder().withoutPadding().encodeToString(publicKey.getEncoded())`
return different values?

**Comment by st-user** [comment]
Yes, they generates **different** values.

 - a) `vapidKeyPair.extractPublicKeyInUncompressedForm()` generates a sequence encoded in the uncompressed form described in [ANSI-X9-62] Annex A (that is, 65 octets, starting with an 0x04 octet)
 - b) `publicKey.getEncoded()` generates  a sequence encoded according to the X.509 standard.

'a)' can be set to `applicationServerKey`. On the other hand, 'b)' can be used to generate `ECPublicKey` objects(like `ECPublicKey ecPublicKey = (ECPublicKey) keyFactory.generatePublic(new X509EncodedKeySpec(...a byte sequence...))`).

**Comment by fenix-hub** [comment]
Thank you very much for your help!

**Comment by st-user** [comment]
I'm interested in it. Please let me know if you like.

Why do you want to generate the key pair directly from java instead of using openssl commands?
(Do you want to programmatically store the key pair in some storage?)

**Comment by fenix-hub** [comment]
Yes that's exactly my objective. Like a multi-tenancy push notification manager.
So I need to programmatically generate keyPairs and (eventually) retreive ones for recognized tenants.
