### ISSUE TITLE
Connection timed out from FCM after sending some Push messages

### ISSUE THREAD

**Issue by fenix-hub** [st-user/zerodep-web-push-java#22]
Yesterday I was testing sending some push messages to an FCM endpoint, but suddenly my backend was not responding to my requests.
Investigating a little bit looks like the FCM server is not responding anymore to my requests.

```java
[...]
HttpRequest httpRequest = StandardHttpClientRequestPreparer.getBuilder()
  .pushSubscription(mapperService.getUserSubscriptionDto(userSubscription).getSubscription())
  .pushMessage(objectMapper.writerWithView(Views.NoRecipients.class).writeValueAsBytes(notificationDto))
  .topic(notificationDto.getSubject())
  .ttl(1, TimeUnit.HOURS)
  .urgency(notificationDto.getPriority())
  .vapidJWTExpiresAfter(15, TimeUnit.MINUTES)
  .vapidJWTSubject(notificationDto.getTenant())
  .build(vapidKeyPair)
  .toRequest();
Integer resultCode = httpClient.send(httpRequest, HttpResponse.BodyHandlers.ofString()).statusCode();
pushResponseList.add(
	PushResponseDto.builder()
	.subscriptionId(userSubscription.getId())
	.resultCode(resultCode)
	.build()
);
} catch (JsonProcessingException e) {
	throw new InternalServerErrorException("Could not create Push Message", e);
} catch (IOException e) {
	throw new InternalServerErrorException("Could not send Push Message", e);
} catch (InterruptedException e) {
	// TODO Auto-generated catch block
	e.printStackTrace();
}
```
The execution stops at `httpClient.send()`, and after a while it throws the `IOException`.
The cause of the exception is:
```java
Caused by: java.net.ConnectException: Connection timed out: no further information
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:561)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        ... 72 more
Caused by: java.net.ConnectException: Connection timed out: no further information
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection$ConnectEvent.handle(PlainHttpConnection.java:128)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:957)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:912)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:912)
```

**Comment by fenix-hub** [comment]
The same code works fine with a Mozilla endpoint by the way.

**Comment by st-user** [comment]
I can't reproduce the error. I can send successfully push messages to the FCM endpoint like `https://fcm.googleapis.com/fcm/send/d4zbW......AG`;

Because this library doesn't handle network connections directly, 
I think this error is caused by a network problem like this.
[HttpClient hits timeout but server is available and working flawlessly](https://stackoverflow.com/questions/67251395/httpclient-hits-timeout-but-server-is-available-and-working-flawlessly)

**Comment by fenix-hub** [comment]
That's very strange.
I added the argument when launching my jar, and it worked with a first call, but now even with the argument it doesn't work anymore.

**Comment by fenix-hub** [comment]
Ok, after some more tests it looks like if I send them from localhost, everything works, but if my app is run inside a docker container now Mozilla endpoints don't work enymore (but FCM ones do)

**Comment by st-user** [comment]
It is unlikely, but if the problem is specific to the JDK's HttpClient, using a third-party library such as `OkHttp` may solve the problem.

``` java

        OkHttpClient httpClient = new OkHttpClient();
        for (PushSubscription subscription : getSubscriptionsFromStorage()) {
            Request request = OkHttpClientRequestPreparer.getBuilder()
                .pushSubscription(subscription)
                .vapidJWTExpiresAfter(15, TimeUnit.MINUTES)
                .vapidJWTSubject("mailto:example@example.com")
                .pushMessage(message)
                .ttl(1, TimeUnit.HOURS)
                .urgencyLow()
                .topic("MyTopic")
                .build(vapidKeyPair)
                .toRequest();
            try (Response response = httpClient.newCall(request).execute()) {
                logger.info(String.format("[OkHttp] status code: %d", response.code()));
            }
        }

```

``` xml

            <dependency>
                <groupId>org.apache.httpcomponents.client5</groupId>
                <artifactId>httpclient5</artifactId>
                <version>5.1.3</version>
            </dependency>

```

(For more information https://github.com/st-user/zerodep-web-push-java-example/blob/main/src/main/java/org/example/BasicExample.java#L111)

**Comment by fenix-hub** [comment]
Looks like OkHttpClient actually solved the issue.
The default HttpClient goes into timeout not because the fcm/mozilla server is not responding, but because it is taking *too long* (around ~2 min to get a response).
Eventually the default HttpClient throws a timeout and I never receive a response.
What really looks strange to me is that after trying with a first request using the OkHttpClient, all next requests are faster like they should be.
It's like *somewhere* there was a queue of all pending requests that were interrupted due to my client timeout, and once the OkHttpClient request was executed the queue was flushed.

**Comment by st-user** [comment]
> The default HttpClient goes into timeout not because the fcm/mozilla server is not responding, but because it is taking too long (around ~2 min to get a response).

If so, the following may also solve the problem. 

``` java
        // java.net.http.HttpClient
        HttpClient httpClient = HttpClient.newBuilder()
            .connectTimeout(Duration.ofMinutes(5))
            .build();

```
